site_name: BioMCP
repo_url: https://github.com/genomoncology/biomcp
site_url: https://biomcp.org/
site_description: Biomedical Model Context Protocol Server
site_author: Ian Maurer
edit_uri: edit/main/docs/
repo_name: genomoncology/biomcp
copyright: Maintained by <a href="https://genomoncology.com">genomoncology</a>.

nav:
  - Home: index.md
  - Tutorials:
      - AlphaGenome Prompts: tutorials/alphagenome-prompts.md
      - AlphaGenome Docker: tutorials/docker-alphagenome.md
      - AlphaGenome Setup: tutorials/alphagenome-setup.md
      - Claude Desktop: tutorials/claude-desktop.md
      - Claude Desktop, for Macos and containerized: tutorials/macos-claude-desktop-dockerized-biomcp.md
      - Cloudflare Worker Deployment: tutorials/cloudflare-worker-deployment.md
      - Cursor IDE: tutorials/cursor-ide.md
      - Logging with BigQuery: tutorials/bigquery_logging.md
      - MCP Client: tutorials/mcp-client.md
      - MCP Inspector: tutorials/mcp-inspector.md
      - Python SDK: tutorials/python-sdk.md
      - Setting Up Stytch OAuth for BioMCP: tutorials/stytch_oauth_setup.md
  - CLI Reference:
      - Articles: cli/articles.md
      - Health Check: cli/health.md
      - Trials: cli/trials.md
      - Variants: cli/variants.md
  - API Reference:
      - cBioPortal: apis/cbioportal.md
      - ClinicalTrials.gov: apis/clinicaltrials_gov.md
      - MyVariant.info: apis/myvariant_info.md
      - PubTator3: apis/pubtator3_api.md
  - Blog:
      - AI Assisted Clinical Trial Search: blog/ai-assisted-clinical-trial-search-analysis.md
      - Deep Researcher Persona: blog/researcher-persona-resource.md
      - What is BioMCP?: blog/what-is-biomcp.md
  - Policies:
      - Privacy Policy: policies/biomcp-privacy.md
      - Security Policy: policies/biomcp-security.md
      - Terms & Conditions: policies/biomcp-terms.md
  - Troubleshooting:
      - MacOS: troubleshooting/macos.md
  - About GenomOncology: genomoncology.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/biomcp"]
theme:
  name: material
  # custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/icon.png
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/genomoncology/biomcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/biomcp-python

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  # Consider adding other useful extensions:
  - admonition # Nice looking note/warning boxes
  - pymdownx.details # Collapsible sections
  - pymdownx.highlight: # Code highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # Include content from other files
  - pymdownx.superfences # Nested code blocks/diagrams
  - pymdownx.tabbed: # Tabbed content
      alternate_style: true
