# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image with version 3.10
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install dependencies from pyproject.toml using uv
# We will install uv first to use it for dependency management
RUN pip install uv

# Install the project's dependencies using the lockfile
RUN uv sync --frozen --no-install-project --no-dev --no-editable

# Set environment variables for the API keys
ENV SEMANTIC_SCHOLAR_API_KEY=your_key_here
ENV CROSSREF_API_KEY=your_key_here

# Expose the port that the server will run on
EXPOSE 8000

# Command to run the server
CMD ["uv", "run", "server.py"]
